model: yolov8m.pt
data: D:/MLPrac/configs/dfire.yaml
epochs: 15
imgsz: 640
batch: 32
optimizer: AdamW
lr0: 0.001
cos_lr: true
project: D:/MLPrac/outputs/runs
name: yolov8m_dfire
device: 0
save_period: 10
val: true
plots: true
exist_ok: true
workers: 4